name: jahangir_alom_tamal_221_15_5322_s_application4
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  carousel_slider_plus: ^7.1.0
  smooth_page_indicator: ^1.2.0+3
  responsive_grid_list: ^1.4.0
  another_stepper: ^1.2.2
  step_progress_indicator: ^1.0.2
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/ArchivoBold.ttf
          weight: 700
        - asset: assets/fonts/ArchivoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ArchivoRegular.ttf
          weight: 400
        - asset: assets/fonts/ArchivoMedium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400